# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
# deleteDatasources:
#   - name: Telegraf
#     orgId: 1
#   - name: Luftdaten
#     orgId: 1

# list of datasources to insert/update 
datasources:
- name: ${DS_TELEGRAF}
  type: influxdb
  access: proxy
  orgId: 1
  url: http://influxdb:8086
  password: "admin"
  user: "admin"
  database: "${DS_TELEGRAF}" # not sure whether the [configuration.env] file will be applied at this level, so harcoded for now "${DS_TELEGRAF}
  basicAuth: false
  isDefault: true
  jsonData:
    timeInterval: "5s"
  version: 1
  editable: false
- name: ${DS_FEINSTAUBSENSOR}
  type: influxdb
  access: proxy
  orgId: 1
  url: http://influxdb:8086
  database: "${DS_FEINSTAUBSENSOR}" # not sure whether the [configuration.env] file will be applied at this level, so harcoded for now "${DS_FEINSTAUBSENSOR}"
  basicAuth: false
  jsonData:
    timeInterval: "5s"
  version: 1
  editable: false
